# Generated by Django 4.2.5 on 2023-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_remove_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter title of the article', max_length=20)),
                ('summury', models.TextField(help_text='enter summury of the article', max_length=100)),
                ('image', models.ImageField(help_text='Enter article photo', upload_to='images/article_photos/')),
                ('content', models.TextField(help_text='enter content of the article')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='images/profile_photos/profile_icon.png', help_text='Enter profile photo', upload_to='images/profile_photos/'),
            preserve_default=False,
        ),
    ]
