# Generated by Django 4.2.5 on 2023-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_article_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summury',
            field=models.TextField(help_text='enter summury of the article', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='enter title of the article', max_length=100),
        ),
    ]
