# Generated by Django 4.2.5 on 2023-09-06 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_article_summury_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 9, 29, 47, 753511)),
        ),
    ]
