# Generated by Django 4.2.5 on 2023-09-06 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 9, 30, 16, 34721)),
        ),
    ]
